E0s: average
batch_size: 10
checkpoints_dir: MACE_models
correlation: 3
device: cuda
energy_key: energy_xtb
forces_key: forces_xtb
log_dir: MACE_models
max_L: 1
max_ell: 2
max_num_epochs: 50
model: MACE
model_dir: MACE_models
name: mace_benchmark_maxL1_corr3
num_channels: 32
num_interactions: 2
r_max: 4.0
results_dir: MACE_models
seed: 123
swa: true
test_file: data/solvent_xtb_test.xyz
train_file: data/solvent_xtb_train_200.xyz
valid_fraction: 0.1
